### ISSUE TITLE
Resource interpreted as Document but transferred with MIM type application/octet-stream

### ISSUE THREAD

**Issue by cgarciajr** [robbederks/downzip#1]
In chrome, I get the warning above.  The resulting zip is around 15 bytes.  In the Chrome Network developer tool I see the downloading of the zip contents (~9MB).  Any tips or clues on how to solve this?

**Comment by robbederks** [comment]
Sorry for the late reply!

According to https://stackoverflow.com/questions/6587393/resource-interpreted-as-document-but-transferred-with-mime-type-application-zip, this might be fixed by adding the `download` attribute to the `<a/>` you're using to start the download. Can you try that?
