### ISSUE TITLE
Documentation file array format

### ISSUE THREAD

**Issue by ricky11** [robbederks/downzip#12]
In the documentation it says to organize the file array in the following format 

const files = [
    {
        name: 'picture1.jpg' 
        downloadUrl: 'http://your-download-url.com/picture1.jpg'
        size: 1234      // In bytes
    }, 
    {
        name: 'picture2.jpg' 
        downloadUrl: 'http://your-download-url.com/picture2.jpg'
        size: 4567      // In bytes
    }
]

however in the downzip.js file in node_modules their is a comment that says 
 // Files array is in the following format: [{name: '', url: ''}, ...]

does it matter if its url or downloadUrl ?, does the order matter?

**Comment by 153957** [comment]
It should be `downloadUrl`. Here is the code using the downloadUrl: https://github.com/robbederks/downzip/blob/master/src/downzip-sw.js#L86

**Comment by robbederks** [comment]
Thanks for pointing this out, fixed
