### ISSUE TITLE
mapScriptUrl not called in the latest build

### ISSUE THREAD

**Issue by keith-waters** [robbederks/downzip#20]
When we swapped back over to your recently updated `npm package`, it wasn't working for us. Seem like the issue is `mapScriptUrl` never gets called by `service-worker-loader`. 

I think another re-build of the package may solve it?

**Comment by coleshaw** [comment]
I ran into this -- I think it's because of a change in `service-worker-loader` in version `4.0.2`? Pinning that to `4.0.0` seems to have helped us.

**Comment by robbederks** [comment]
Would appreciate a PR to either pin the version or fix it to work with the latest one!

**Comment by coleshaw** [comment]
Oh, whelp, upon further investigation should ignore my suggestion about pinning versions -- I think it was just something with my local `node_modules` :facepalm:  Still run into the same issue.

**Comment by robbederks** [comment]
Should be fixed (see #28)
