### ISSUE TITLE
Feature request: Directories

### ISSUE THREAD

**Issue by gunar** [robbederks/downzip#22]
It'd be useful to be able to create directories inside the generated zip file and place files inside these sub-directories.

Any idea how much work that would entail?

> ~It seems you're already using `jszip` so it _should_ be relatively straightforward.~ EDIT: jszip is only used in tests, in such case I recommend moving it from `dependencies` into `devDependencies`.

**Comment by robbederks** [comment]
Shouldn't be too hard, just have to add it to the zip generator. Feel free to make a PR!

**Comment by gunar** [comment]
@robbederks It might take me a while to get the hang of this codebase and the zip file-type. Hope you're not offended but is there any chance my company can pay you or someone or build the feature? Consider it a bounty program. Can you give me a quote?

**Comment by robbederks** [comment]
I'm sorry, I'm not taking in any more work atm. In any case, I still stand by the fact that this should be simple to add in a PR by anyone with some JS skills and the zip64 spec.

I think it's a great added feature, so I'll leave this issue open for now

**Comment by gunar** [comment]
It works out of the box. Just include the relative path (using forward slashes) in the filenames.

    4.4.17 file name: (Variable)

       4.4.17.1 The name of the file, with optional relative path.
       The path stored MUST NOT contain a drive or
       device letter, or a leading slash.  All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility with Amiga
       and UNIX file systems etc.  If input came from standard
       input, there is no file name field.

**Comment by robbederks** [comment]
Even better!
