### ISSUE TITLE
Getting error while integrating this in React project

### ISSUE THREAD

**Issue by vinodkhandelwal** [robbederks/downzip#23]
Hi,

I am trying to integrate this library in a react project but not able to make it work .

I am getting below error. 

``
The script has an unsupported MIME type ('text/html').
[DownZip-Main] [DownZip] Service workers not loaded:
[DownZip-Main] [DownZip] No service worker registered!
Uncaught (in promise) TypeError: Cannot read property 'postMessage' of null
``
Is there any guideline or sample project on how to use this in react project.

**Comment by robbederks** [comment]
You can check out the example in the README, and projects having downzip as a dependency.
Feel free to re-open if this is still an issue.

**Comment by ErlanBazarov** [comment]
@vinodkhandelwal Were you able to solve the issue? I am facing the same issue. I am using React that was created with Create React App
