### ISSUE TITLE
make sure serviceWorker is registered before running

### ISSUE THREAD

**Issue by evliu** [robbederks/downzip#7]
since this lib handles registering the service worker, should the service worker be manually checked or maybe async/await the construction of the DownZip object?

**Comment by robbederks** [comment]
The loading result is checked here: https://github.com/robbederks/downzip/blob/d1bfc82a9e7e9635f9065d0b122ab728523283dc/src/downzip.js#L17

Not sure how to best handle the not-loading, but I'd be happy to get a PR with a good implementation.

**Comment by ricky11** [comment]
Can we use this module without service workers?
